### ISSUE TITLE
Support use as a node module

### ISSUE THREAD

**Issue by mcwhittemore** [wayspurrchen/byebyte#2]
Way,

How would you feel about a PR that converts this into something that can be required? The CLI would stay of course :).

Here is how I see the API working:

```js
var byebyte = require('byebyte');
var fs = require('fs');
var input = fs.readFileSync('./some-file.jpg');

var shuffled = byebyte. shuffle(input, {});
fs.writeFileSync('./some-suffled-file.jpg');
```

I'm more than happy to put together a PR for this, I just wanted to get your thoughts first.

My plan is to move `index.js` to `bin/cli.js` and port the non-arg parsing logic back to `index.js` which will be exposed when `require('byebyte')` is invoked. As far as I can tell, right now when `require('byebyte')` is invoked `undefined` is returned so this change shouldn't be breaking.

Thanks for your thoughts,
Matthew

**Comment by wayspurrchen** [comment]
Hey! This would be great, feel free to open a PR. :)
