### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by agargara** [wayspurrchen/byebyte#4]
Hello, and thank you for this wonderful and beautiful tool!
I love it very much.

After updating to 1.0 I was faced with the error:
```
env: node\r: No such file or directory
```

After some searching, I discovered this seems to be a common issue with Node.js when using files with Windows line endings. See: https://github.com/npm/npm/issues/12371

I was able to fix it with the following:
```
$ brew install dos2unix
$ sudo dos2unix /usr/local/lib/node_modules/byebyte/commands/cli.js 
```

If you have a way to easily save your scripts with Unix line endings, I think it would be most helpful for those of us on linux or OSX. Thanks!

**Comment by wayspurrchen** [comment]
Hi, thanks so much for reporting this! This is now fixed in version 1.2.1. ❤️
